// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoG_AApdh41yLcCsV4JTJs5P-9pFUNWUg',
    appId: '1:205366376782:web:534a2eade1a204ebe1461f',
    messagingSenderId: '205366376782',
    projectId: 'alanya-9233f',
    authDomain: 'alanya-9233f.firebaseapp.com',
    storageBucket: 'alanya-9233f.firebasestorage.app',
    measurementId: 'G-VTGC968PFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJehfBBKxyKxWoX4161gAAR5I-jJPj3Uw',
    appId: '1:205366376782:android:35a2f010a750c4ade1461f',
    messagingSenderId: '205366376782',
    projectId: 'alanya-9233f',
    storageBucket: 'alanya-9233f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPmNTuwiiblUc8H8klDDcT90KKQG4-m5k',
    appId: '1:205366376782:ios:4e3d62dc4c777eb1e1461f',
    messagingSenderId: '205366376782',
    projectId: 'alanya-9233f',
    storageBucket: 'alanya-9233f.firebasestorage.app',
    iosBundleId: 'com.alanya237.alanya',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPmNTuwiiblUc8H8klDDcT90KKQG4-m5k',
    appId: '1:205366376782:ios:4e3d62dc4c777eb1e1461f',
    messagingSenderId: '205366376782',
    projectId: 'alanya-9233f',
    storageBucket: 'alanya-9233f.firebasestorage.app',
    iosBundleId: 'com.alanya237.alanya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoG_AApdh41yLcCsV4JTJs5P-9pFUNWUg',
    appId: '1:205366376782:web:b827669977bfb554e1461f',
    messagingSenderId: '205366376782',
    projectId: 'alanya-9233f',
    authDomain: 'alanya-9233f.firebaseapp.com',
    storageBucket: 'alanya-9233f.firebasestorage.app',
    measurementId: 'G-1BHKSXCX2Y',
  );
}
